### ISSUE TITLE
Hello @zackmark29

### ISSUE THREAD

**Issue by alfredocesar** [zackmark29/viu.com_m3u8_parser#2]
Excelent Work Zack I have already test this on Viu.

Have a great day!!!

**Comment by zackmark29** [comment]
Hi sorry I can't share my viki tool because it's included drm already.
It's just my private tool.

**Comment by alfredocesar** [comment]
Hello zackmark.
We work at a small business that relies on selling movies and tv-shows
based on clients demands.
Of course I live in a country with no laws for copyright distributions.
I am willing to pay for your viki parser tool and any other updates at the
price you name.
This, of course, is only for my business private use. K-dramas are indeed
on the demmanded content.

Anyway man I will appreciate your help for free if you can explain what is
the current method to download videos from viki using youtube-dl.
I have viki pass plus and i want to download the tv-shows at 1280x720 or
1920x1080.

Any help you can provide me will be more than welcome, Zack.

Have a wonderful day
Thanks
